### ISSUE TITLE
removing screenshot buttons mod

### ISSUE THREAD

**Issue by rubyando** [csgofloat/extension#96] opened 2021-05-20 08:12 UTC
hello I would like to know how to make these green screenshot buttons on float checker dissapear? I don't use them and they take up too much space

![firefox_Kdnvt6j4wv](https://user-images.githubusercontent.com/84499494/118943284-00a9af80-b943-11eb-8309-162df45242c7.png)

my browser is Firefox thx

**Comment by Step7750** [comment] 2023-05-26 05:31
Dupe of #142

**Closed by Step7750** 2023-05-26 05:31 UTC
